# Generated by Django 3.1.14 on 2022-05-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('categoria', models.CharField(choices=[('Basico', 'Basico'), ('Premium', 'Premium')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
                ('ingrediente', models.ManyToManyField(to='pizzas.Ingrediente')),
            ],
        ),
    ]
